apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: prom-node-exporter
    name: prom-node-exporter
  name: prom-node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: prom-node-exporter
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: default
  name: prom-node-exporter
spec:
  template:
    metadata:
      name:  prom-node-exporter
      labels:
        app: prom-node-exporter
      annotations:
        prometheus.io.scrape: "true"
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name:  prom-node-exporter
        image: prom/node-exporter:v0.14.0
        securityContext:
          privileged: true
        ports:
        - containerPort: 9100
