version: '2'

services:

  # Note: add 127.0.0.1 logstash to /etc/hosts
  webapp-python-1:
    build: webapp-python
    ports:
      - "8001:8080"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:12201"
    depends_on:
      - logstash

  elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    # xpack.security.enabled=false
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    build: logstash
    ports:
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    build: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      # admin user: elastic
      ELASTICSEARCH_PASSWORD: secret
    depends_on:
      - elasticsearch
